### PR TITLE
Add possiblity to sort by date Backtesting data file

### PR DESCRIPTION
**Pull request by valouvaliavlo**
depends on : https://github.com/Drakkar-Software/OctoBot-Backtesting/pull/127

### CODE REVIEW

**Review by GuillaumeDSM — APPROVED** [review]
💯

**Review by Herklos — APPROVED** [review]
Nice 👍

**Comment by Herklos** [comment]
@valouvaliavlo you should update your branch with latest dev commit

**Comment by valouvaliavlo** [comment]
> @valouvaliavlo you should update your branch with latest dev commit

Hi @Herklos, it's done

**Comment by GuillaumeDSM** [comment]
After a last rebase, we will be able to merge this too, thanks @valouvaliavlo !

**Comment by valouvaliavlo** [comment]
> After a last rebase, we will be able to merge this too, thanks @valouvaliavlo !

Done

**Comment by Herklos** [comment]
@valouvaliavlo your merge request shouldn't contains commits from @GuillaumeDSM and me. Could you just propose your 3 main commits ? (instead of 18 here)

**Pull request closed without merging**
