### PR TITLE
[DataCollector] Add long and short test for DataCollector on date range

### PR DESCRIPTION
**Pull request by valouvaliavlo**

### CODE REVIEW

**Comment by GuillaumeDSM** [comment]
Thanks for the tests !
Could you make it a bit smaller though, it really takes a long time to run now 😂 
image

**Comment by valouvaliavlo** [comment]
> Thanks for the tests !
> Could you make it a bit smaller though, it really takes a long time to run now 😂
> image

😂 A half ? Or less ?

**Comment by GuillaumeDSM** [comment]
> > Thanks for the tests !
> > Could you make it a bit smaller though, it really takes a long time to run now 😂
> > image
> 
> 😂 A half ? Or less ?

I guess 40s is ok, could we reduce both `test_collect_valid_date_range` (by half if you think it sill makes sence) and `test_collect_long_range` by 4 (to make it around 40s) ?

**Review by GuillaumeDSM — APPROVED** [review]
👍

**Review by Herklos — APPROVED** [review]

**Pull request merged**
