### PR TITLE
[WebInterface] differentiate read_only profiles in profiles selector

### PR DESCRIPTION
**Pull request by GuillaumeDSM**
image

### CODE REVIEW

**Review by Herklos — COMMENTED** [review]
Good idea, I think we can find an other icon to be more understandable

**Comment by GuillaumeDSM** [comment]
> Good idea, I think we can find an other icon to be more understandable

Agree but I didn't find a better one yet, if you see one, we change it :) 
https://fontawesome.com/v5.15/icons?d=gallery&m=free

**Comment by Herklos** [comment]
> > Good idea, I think we can find an other icon to be more understandable
> 
> Agree but I didn't find a better one yet, if you see one, we change it :)
> I was thinking about a slightly different id-card but they are not different enough, it just looks weird
> https://fontawesome.com/v5.15/icons?d=gallery&m=free

What do you think about https://fontawesome.com/v5.15/icons/user-lock?style=solid ?

**Comment by GuillaumeDSM** [comment]
> > > Good idea, I think we can find an other icon to be more understandable
> > 
> > 
> > Agree but I didn't find a better one yet, if you see one, we change it :)
> > I was thinking about a slightly different id-card but they are not different enough, it just looks weird
> > https://fontawesome.com/v5.15/icons?d=gallery&m=free
> 
> What do you think about https://fontawesome.com/v5.15/icons/user-lock?style=solid ?
> 
> > **[Font Awesome](https://fontawesome.com)**The world’s most popular and easiest to use icon set just got an upgrade. More icons. More styles. More Options.

For read-only profiles and then use the id-card one for custom ones ?

**Comment by Herklos** [comment]
> > > > Good idea, I think we can find an other icon to be more understandable
> > > 
> > > 
> > > Agree but I didn't find a better one yet, if you see one, we change it :)
> > > I was thinking about a slightly different id-card but they are not different enough, it just looks weird
> > > https://fontawesome.com/v5.15/icons?d=gallery&m=free
> > 
> > 
> > What do you think about https://fontawesome.com/v5.15/icons/user-lock?style=solid ?
> > > **[Font Awesome](https://fontawesome.com)**The world’s most popular and easiest to use icon set just got an upgrade. More icons. More styles. More Options.
> 
> For read-only profiles and then use the id-card one for custom ones ?
> 
> > **[Font Awesome](https://fontawesome.com)**The world’s most popular and easiest to use icon set just got an upgrade. More icons. More styles. More Options.

Yes

**Comment by GuillaumeDSM** [comment]
image

**Comment by Herklos** [comment]
> > > > > Good idea, I think we can find an other icon to be more understandable
> > > > 
> > > > 
> > > > Agree but I didn't find a better one yet, if you see one, we change it :)
> > > > I was thinking about a slightly different id-card but they are not different enough, it just looks weird
> > > > https://fontawesome.com/v5.15/icons?d=gallery&m=free
> > > 
> > > 
> > > What do you think about https://fontawesome.com/v5.15/icons/user-lock?style=solid ?
> > > > **[Font Awesome](https://fontawesome.com)**The world’s most popular and easiest to use icon set just got an upgrade. More icons. More styles. More Options.
> > 
> > 
> > For read-only profiles and then use the id-card one for custom ones ?
> > > **[Font Awesome](https://fontawesome.com)**The world’s most popular and easiest to use icon set just got an upgrade. More icons. More styles. More Options.
> 
> Yes
> 
> > **[Font Awesome](https://fontawesome.com)**The world’s most popular and easiest to use icon set just got an upgrade. More icons. More styles. More Options.

I was also thinking about https://fontawesome.com/v5.15/icons/user-shield?style=solid. What do you think ?

We can also use https://fontawesome.com/v5.15/icons/user-cog?style=solid for user's profiles. To provide consistency with the locked profile

**Comment by GuillaumeDSM** [comment]
image

**Review by Herklos — APPROVED** [review]
👍

**Pull request merged**
