### PR TITLE
Multiple minor fixes

### PR DESCRIPTION
**Pull request by techfreaque**
here are my answers to your open qustions:

- [Services] fix commands response before shutdown
we should use a shorter delay

I changed it to 0.1 which I also tested multiple times

### CODE REVIEW

**Comment by techfreaque** [comment]
I see test are failing, I'll take care of that

**Comment by GuillaumeDSM** [comment]
good for me after rebase

**Comment by techfreaque** [comment]
> good for me after rebase

done

**Review by Herklos — APPROVED** [review]
:+1:

**Comment by Herklos** [comment]
Could you remove those merge commits please @techfreaque?

**Comment by techfreaque** [comment]
> Could you remove these merge commits please @techfreaque?

done

**Pull request merged**
