### PR TITLE
[WebInterface][DataCollector] Multi symbol collect

### PR DESCRIPTION
**Pull request by valouvaliavlo**
https://feedback.octobot.online/posts/63/backtesting-of-multiple-pairs

### CODE REVIEW

**Comment by valouvaliavlo** [comment]
I put a maximum number for the selection at 5. It's ok for you?

**Comment by GuillaumeDSM** [comment]
> I put a maximum number for the selection at 5. It's ok for you?

What is the reason for this limit ?

**Review by GuillaumeDSM — COMMENTED** [review]
very good idea, thanks !

**Comment by valouvaliavlo** [comment]
Just to avoid monopolizing the resource for too long, especially if the collection is done with a large row of dates.ut otherwise I had no problem when I tested it with more peers than that

**Comment by GuillaumeDSM** [comment]
> Just to avoid monopolizing the resource for too long, especially if the collection is done with a large row of dates.
> But otherwise I had no problem when I tested it with more peers than that

I guess that's better for now and in the future we will add a progress bar, with it we will be able to increase this limit

**Review by GuillaumeDSM — APPROVED** [review]

**Review by Herklos — APPROVED** [review]

**Pull request merged**
